# Generated by Django 5.2.4 on 2025-08-04 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('assigned', 'Assigned'), ('accepted', 'Accepted'), ('picked_up', 'Picked Up'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='assigned', help_text='Delivery assignment status', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('picked_up_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, help_text='Delivery notes or issues', null=True)),
            ],
            options={
                'verbose_name': 'Delivery Assignment',
                'verbose_name_plural': 'Delivery Assignments',
                'db_table': 'delivery_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryPerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('bicycle', 'Bicycle'), ('motorcycle', 'Motorcycle'), ('car', 'Car'), ('van', 'Van')], help_text='Type of delivery vehicle', max_length=50)),
                ('vehicle_number', models.CharField(blank=True, help_text='Vehicle registration number', max_length=20, null=True)),
                ('license_number', models.CharField(blank=True, help_text='Driving license number', max_length=50, null=True)),
                ('is_available', models.BooleanField(default=True, help_text='Whether delivery person is available for assignments')),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Current latitude for location tracking', max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Current longitude for location tracking', max_digits=9, null=True)),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, help_text='Average delivery rating', max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('total_deliveries', models.PositiveIntegerField(default=0, help_text='Total number of completed deliveries')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Person',
                'verbose_name_plural': 'Delivery Persons',
                'db_table': 'delivery_persons',
            },
        ),
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Zone name', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Zone description', null=True)),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, help_text='Standard delivery fee for this zone', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_delivery_time', models.PositiveIntegerField(help_text='Estimated delivery time in minutes')),
                ('is_active', models.BooleanField(default=True, help_text='Whether the zone is active for deliveries')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Delivery Zone',
                'verbose_name_plural': 'Delivery Zones',
                'db_table': 'delivery_zones',
                'ordering': ['name'],
            },
        ),
    ]
