# Generated by Django 5.2.4 on 2025-08-04 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('delivery', '0001_initial'),
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryassignment',
            name='delivery_person',
            field=models.ForeignKey(help_text='Assigned delivery person', limit_choices_to={'role': 'delivery'}, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deliveryassignment',
            name='order',
            field=models.OneToOneField(help_text='Order being delivered', on_delete=django.db.models.deletion.CASCADE, related_name='delivery_assignment', to='orders.order'),
        ),
        migrations.AddField(
            model_name='deliveryperson',
            name='user',
            field=models.OneToOneField(help_text='User account for delivery person', limit_choices_to={'role': 'delivery'}, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
