# Generated by Django 5.2.4 on 2025-08-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('user_create', 'User Created'), ('user_update', 'User Updated'), ('user_delete', 'User Deleted'), ('shop_approve', 'Shop Approved'), ('shop_reject', 'Shop Rejected'), ('shop_suspend', 'Shop Suspended'), ('order_cancel', 'Order Cancelled'), ('delivery_assign', 'Delivery Assigned'), ('system_setting', 'System Setting Changed')], help_text='Type of action performed', max_length=50)),
                ('target_model', models.CharField(help_text='Target model name', max_length=50)),
                ('target_id', models.PositiveIntegerField(help_text='Target object ID')),
                ('description', models.TextField(help_text='Action description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional action metadata')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Admin Action',
                'verbose_name_plural': 'Admin Actions',
                'db_table': 'admin_actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('order_status', 'Order Status Update'), ('shop_approval', 'Shop Approval'), ('delivery_assignment', 'Delivery Assignment'), ('system_announcement', 'System Announcement'), ('promotion', 'Promotion')], help_text='Type of notification', max_length=50)),
                ('title', models.CharField(help_text='Notification title', max_length=200)),
                ('message', models.TextField(help_text='Notification message')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the notification has been read')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional notification data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, help_text='When the notification was read', null=True)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Setting key', max_length=100, unique=True)),
                ('value', models.TextField(help_text='Setting value')),
                ('description', models.TextField(blank=True, help_text='Setting description', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the setting is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Setting',
                'verbose_name_plural': 'System Settings',
                'db_table': 'system_settings',
                'ordering': ['key'],
            },
        ),
    ]
