# Generated by Django 5.2.4 on 2025-08-04 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Shop name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Shop description', null=True)),
                ('address', models.TextField(help_text='Shop address')),
                ('phone', models.CharField(help_text='Shop contact phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, help_text='Shop contact email', max_length=254, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('suspended', 'Suspended'), ('rejected', 'Rejected')], default='pending', help_text='Shop approval status', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the shop is currently active')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Shop latitude for location services', max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Shop longitude for location services', max_digits=9, null=True)),
                ('opening_time', models.TimeField(blank=True, help_text='Shop opening time', null=True)),
                ('closing_time', models.TimeField(blank=True, help_text='Shop closing time', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
                'db_table': 'shops',
                'ordering': ['-created_at'],
            },
        ),
    ]
