# Generated by Django 5.2.4 on 2025-08-04 15:12

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique order identifier', unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('packed', 'Packed'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', help_text='Order status', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', help_text='Payment status', max_length=20)),
                ('delivery_address', models.TextField(help_text='Delivery address')),
                ('delivery_phone', models.CharField(help_text='Delivery contact phone', max_length=17)),
                ('notes', models.TextField(blank=True, help_text='Order notes or special instructions', null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total order amount', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('delivery_fee', models.DecimalField(decimal_places=2, default=0, help_text='Delivery fee', max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('estimated_delivery_time', models.DateTimeField(blank=True, help_text='Estimated delivery time', null=True)),
                ('actual_delivery_time', models.DateTimeField(blank=True, help_text='Actual delivery time', null=True)),
                ('otp', models.CharField(blank=True, help_text='OTP for delivery verification', max_length=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(help_text='Quantity of the product', validators=[django.core.validators.MinValueValidator(1)])),
                ('unit_price', models.DecimalField(decimal_places=2, help_text='Unit price at the time of order', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('total_price', models.DecimalField(decimal_places=2, help_text='Total price for this item (quantity * unit_price)', max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'order_items',
            },
        ),
    ]
